org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=1G -XX:ReservedCodeCacheSize=512m -XX:+UseG1GC -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false

# Enable Gradle Parallel execution, Daemon & Build Cache for fast compilation
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.daemon=true

# Fix cross-drive (C: vs D:) Kotlin incremental build daemon cache issue
kotlin.incremental=false
kotlin.compiler.daemon=false
